apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  namespace: external-systems
  description: Petstore
  annotations:
    argocd/app-name: cds
spec:
  type: service
  lifecycle: experimental
  owner: group:pet-managers
